export interface MusicSongObject {
    disc?: string
    track?: number
    url: string
}

export interface ImageObject {
    height?: number
    type?: string
    url: string
    width?: number
    alt?: string
}

export interface VideoObject {
    height?: number
    type?: string
    url: string
    width?: number
}

export interface TwitterImageObject {
    alt?: string
    height?: number
    url: string
    width?: number
}
export interface TwitterPlayerObject {
    height?: number
    stream?: string
    url: string
    width?: number
}

export interface OgObjectInternal {
    alAndroidAppName?: string
    alAndroidClass?: string
    alAndroidPackage?: string
    alAndroidUrl?: string
    alIosAppName?: string
    alIosAppStoreId?: string
    alIosUrl?: string
    alIpadAppName?: string
    alIpadAppStoreId?: string
    alIpadUrl?: string
    alIphoneAppName?: string
    alIphoneAppStoreId?: string
    alIphoneUrl?: string
    alWebShouldFallback?: string
    alWebUrl?: string
    alWindowsAppId?: string
    alWindowsAppName?: string
    alWindowsPhoneAppId?: string
    alWindowsPhoneAppName?: string
    alWindowsPhoneUrl?: string
    alWindowsUniversalAppId?: string
    alWindowsUniversalAppName?: string
    alWindowsUniversalUrl?: string
    alWindowsUrl?: string
    articleAuthor?: string
    articleExpirationTime?: string
    articleModifiedTime?: string
    articlePublishedDate?: string
    articlePublishedTime?: string
    articleModifiedDate?: string
    articlePublisher?: string
    articleSection?: string
    articleTag?: string
    author?: string
    bookAuthor?: string
    bookCanonicalName?: string
    bookIsbn?: string
    bookReleaseDate?: string
    booksBook?: string
    booksRatingScale?: string
    booksRatingValue?: string
    bookTag?: string
    businessContactDataCountryName?: string
    businessContactDataLocality?: string
    businessContactDataPostalCode?: string
    businessContactDataRegion?: string
    businessContactDataStreetAddress?: string
    charset?: string
    customMetaTags?: Record<string, string | string[]>
    dcContributor?: string
    dcCoverage?: string
    dcCreator?: string
    dcDate?: string
    dcDateCreated?: string
    dcDateIssued?: string
    dcDescription?: string
    dcFormatMedia?: string
    dcFormatSize?: string
    dcIdentifier?: string
    dcLanguage?: string
    dcPublisher?: string
    dcRelation?: string
    dcRights?: string
    dcSource?: string
    dcSubject?: string
    dcTitle?: string
    dcType?: string
    error?: string
    errorDetails?: Error
    favicon?: string
    fbAppId?: string
    jsonLD?: object[]
    modifiedTime?: string
    musicAlbum?: string
    musicAlbumDisc?: string
    musicAlbumTrack?: string
    musicAlbumUrl?: string
    musicCreator?: string
    musicDuration?: string
    musicMusician?: string
    musicPlaylist?: string
    musicRadioStation?: string
    musicReleaseDate?: string
    musicSong?: MusicSongObject[]
    musicSongDisc?: string[]
    musicSongProperty?: string[]
    musicSongTrack?: string[]
    musicSongUrl?: string[]
    ogArticleAuthor?: string
    ogArticleExpirationTime?: string
    ogArticleModifiedTime?: string
    ogArticlePublishedTime?: string
    ogArticlePublisher?: string
    ogArticleSection?: string
    ogArticleTag?: string
    ogAudio?: string
    ogAudioSecureURL?: string
    ogAudioType?: string
    ogAudioURL?: string
    ogAvailability?: string
    ogDate?: string
    ogDescription?: string
    ogDeterminer?: string
    ogEpisode?: string
    ogImage?: ImageObject[]
    ogImageAlt?: string[]
    ogImageHeight?: string[]
    ogImageProperty?: string[]
    ogImageSecureURL?: string[]
    ogImageType?: string[]
    ogImageURL?: string[]
    ogImageWidth?: string[]
    ogLocale?: string
    ogLocaleAlternate?: string
    ogLogo?: string
    ogMovie?: string
    ogPriceAmount?: string
    ogPriceCurrency?: string
    ogProductAvailability?: string
    ogProductCondition?: string
    ogProductPriceAmount?: string
    ogProductPriceCurrency?: string
    ogProductRetailerItemId?: string
    ogSiteName?: string
    ogTitle?: string
    ogType?: string
    ogUrl?: string
    ogVideo?: VideoObject[]
    ogVideoActor?: string
    ogVideoActorId?: string
    ogVideoActorRole?: string
    ogVideoDirector?: string
    ogVideoDuration?: string
    ogVideoHeight?: string[]
    ogVideoOther?: string
    ogVideoProperty?: string[]
    ogVideoReleaseDate?: string
    ogVideoSecureURL?: string
    ogVideoSeries?: string
    ogVideoTag?: string
    ogVideoTvShow?: string
    ogVideoType?: string[]
    ogVideoWidth?: string[]
    ogVideoWriter?: string
    ogWebsite?: string
    placeLocationLatitude?: string
    placeLocationLongitude?: string
    profileFirstName?: string
    profileGender?: string
    profileLastName?: string
    profileUsername?: string
    publishedTime?: string
    releaseDate?: string
    requestUrl?: string
    restaurantContactInfoCountryName?: string
    restaurantContactInfoEmail?: string
    restaurantContactInfoLocality?: string
    restaurantContactInfoPhoneNumber?: string
    restaurantContactInfoPostalCode?: string
    restaurantContactInfoRegion?: string
    restaurantContactInfoStreetAddress?: string
    restaurantContactInfoWebsite?: string
    restaurantMenu?: string
    restaurantRestaurant?: string
    restaurantSection?: string
    restaurantVariationPriceAmount?: string
    restaurantVariationPriceCurrency?: string
    success?: boolean
    twitterAccount?: string
    twitterAppIdGooglePlay?: string
    twitterAppIdiPad?: string
    twitterAppIdiPhone?: string
    twitterAppNameGooglePlay?: string
    twitterAppNameiPad?: string
    twitterAppNameiPhone?: string
    twitterAppUrlGooglePlay?: string
    twitterAppUrliPad?: string
    twitterAppUrliPhone?: string
    twitterCard?: string
    twitterCreator?: string
    twitterCreatorId?: string
    twitterDescription?: string
    twitterImage?: TwitterImageObject[]
    twitterImageAlt?: string[]
    twitterImageHeight?: string[]
    twitterImageProperty?: string[]
    twitterImageSrc?: string[]
    twitterImageWidth?: string[]
    twitterPlayer?: TwitterPlayerObject[]
    twitterPlayerHeight?: string[]
    twitterPlayerProperty?: string[]
    twitterPlayerStream?: string[]
    twitterPlayerStreamContentType?: string
    twitterPlayerWidth?: string[]
    twitterSite?: string
    twitterSiteId?: string
    twitterTitle?: string
    twitterUrl?: string
    updatedTime?: string
}
export type OgObject = Omit<OgObjectInternal, 'musicSongDisc' | 'musicSongProperty' | 'musicSongTrack' | 'musicSongUrl' | 'ogImageAlt' | 'ogImageHeight' | 'ogImageProperty' | 'ogImageSecureURL' | 'ogImageType' | 'ogImageURL' | 'ogImageWidth' | 'ogVideoHeight' | 'ogVideoProperty' | 'ogVideoType' | 'ogVideoWidth' | 'twitterImageAlt' | 'twitterImageHeight' | 'twitterImageProperty' | 'twitterImageSrc' | 'twitterImageWidth' | 'twitterPlayerHeight' | 'twitterPlayerProperty' | 'twitterPlayerStream' | 'twitterPlayerWidth'>
