import type { Metadata } from 'next'
import { IBM_Plex_Sans, IBM_Plex_Mono } from 'next/font/google'
import './globals.css'
import ReactQueryProvider from '@/providers/ReactQueryProvider'
import RouteChangeProgress from '@/providers/RouteChangeProgress'
import { Toaster } from '@/components/ui/sonner'

const ibmSans = IBM_Plex_Sans({
    variable: '--font-ibm-sans',
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700'],
    display: 'swap'
})

const ibmMono = IBM_Plex_Mono({
    variable: '--font-ibm-mono',
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
    display: 'swap'
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${ibmSans.variable} ${ibmMono.variable} antialiased bg-background text-foreground font-sans`}
            >
                <ReactQueryProvider>
                    <RouteChangeProgress>
                        {children}
                        <Toaster richColors position='top-center' />
                    </RouteChangeProgress>
                </ReactQueryProvider>
            </body>
        </html>
    )
}
